spring.application.name=asturias-ruta-ride

# Base
api-endpoint=/api/v1

# Profile
spring.profiles.active=mysql

# Docker Compose
spring.docker.compose.enabled=true

# Spring Security
spring.security.user.name=myuser
spring.security.user.password=secret

# Config Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=u4369154860@gmail.com
spring.mail.password=jrtw lqfl dujo dtqi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true