spring.application.name=asturias-ruta-ride

# Base
api-endpoint=/api/v1

# Profile
spring.profiles.active=mysql

# Docker Compose
spring.docker.compose.enabled=true

# Spring Security
spring.security.user.name=myuser
spring.security.user.password=secret