spring.application.name=asturias-ruta-ride

# Base
api-endpoint=/api/v1

# Profile
spring.profiles.active=mysql

# Docker Compose
spring.docker.compose.enabled=true

# DataSource Config 
spring.datasource.url=jdbc:mysql://localhost:3306/asturias-ruta-ride?useSSL=false&serverTimezone=UTC
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true   

# Spring Security
spring.security.user.name=${SPRING_DATASOURCE_USERNAME}
spring.security.user.password=${SPRING_DATASOURCE_PASSWORD}